//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Employees_DBEntities : DbContext
    {
        public Employees_DBEntities()
            : base("name=Employees_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Transection> Transection { get; set; }
        public virtual DbSet<TransectionType> TransectionType { get; set; }
    }
}
