//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public int CustomerID { get; set; }
        public string NationalID { get; set; }
        public string FullName { get; set; }
        public System.DateTime BirthDay { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string imagee { get; set; }
    }
}
